# Python 3.9 베이스 이미지
FROM python:3.9

# 작업 디렉토리 설정
WORKDIR /app

# Python dependencies 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# Flask 서버 실행
CMD ["python", "similarity.py"]
