name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            sudo usermod -aG docker ${{ secrets.SSH_USER }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest
            docker stop lab-backend || true
            docker rm lab-backend || true
            docker run -d --name lab-backend -p 3000:3000 \
              -e MONGODB_URL=${{ secrets.MONGODB_URL }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
              -e REDIS_URL=${{ secrets.REDIS_URL }} \
              -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              -e SQS_REGION=${{ secrets.SQS_REGION }} \
              -e QUIZ_QUEUE_URL=${{ secrets.QUIZ_QUEUE_URL }} \
              -e REPORT_QUEUE_URL=${{ secrets.REPORT_QUEUE_URL }} \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest
          EOF
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
