name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          cd frontend
          yarn install
          yarn build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          # 서버에 연결하여 html 디렉토리 생성
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /home/${{ secrets.SSH_USER }}/html/"
          # 빌드된 파일을 서버로 복사
          scp -r frontend/build/* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/html/
          # 서버에 연결하여 배포 처리
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            docker-compose -f /home/${{ secrets.SSH_USER }}/docker-compose.yml up -d nginx
            docker cp /home/${{ secrets.SSH_USER }}/html/. nginx:/usr/share/nginx/html/
            docker-compose -f /home/${{ secrets.SSH_USER }}/docker-compose.yml restart nginx
          EOF
