name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            if [ ! -f /path/to/.env ]; then
              touch /path/to/.env
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest
            docker stop lab-backend || true
            docker rm lab-backend || true
            docker run -d --name lab-backend -p 3000:3000 --env-file /path/to/.env ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest
          EOF
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SQS_REGION: ${{ secrets.SQS_REGION }}
          SQS_URL: ${{ secrets.SQS_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

