name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # 사용 중인 Node.js 버전으로 변경

      - name: Install dependencies and build
        run: |
          cd frontend
          yarn install
          yarn build

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # 빌드된 정적 파일을 서버의 Nginx 컨테이너 디렉토리로 복사
            rsync -av --delete frontend/build/ /path/to/nginx/html/

            # 백엔드 컨테이너 업데이트
            docker pull ${{ secrets.DOCKER_USERNAME }}/lab-backend:latest
            docker stop lab-backend || true
            docker rm lab-backend || true
            docker-compose -f /home/ubuntu/docker-compose.yml up -d lab-backend nginx
          EOF
